name: Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      release_type: stable
      tag: r123
    secrets: inherit
