name: Build

on:
  push:
    branches:
      - master
jobs:
  ubuntu:
    name: Linux Static Natives ${{ matrix.arch }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch:
          - "x86"
          - "x86-64"
          - "arm64"
          - "ppc64el"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages for native build
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          dpkg -l
          ls -al /etc/apt/sources.list.d/
          cat /etc/apt/sources.list
          sudo rm -f /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-focal.list
          sudo apt-get remove --purge g++-9 g++-10
          sudo apt-get autoremove --purge
          if [ "${{ matrix.arch }}" != "i386" ] && [ "${{ matrix.arch }}" != "x86-64" ]; then
            sudo cp -f ubuntu-build-image/ports-sources.list /etc/apt/sources.list
          fi
          sudo ./ubuntu-build-image/packages.sh ${{ matrix.arch }} ${{ env.RELEASE_JAVA_VERSION }}
