name: Build

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      release_type: stable
      tag: r123
    secrets:
      IN_ENV_SECRET: ${{ secrets.ENV_SECRET }}
      ENV_SECRET: ${{ secrets.ENV_SECRET }}
      ACTION_SECRET: ${{ secrets.ACTION_SECRET }}
