on:
  schedule:
    - cron: '*/140 * * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: dl
        run: curl -s https://nexus.ingo.ch/jitsi-desktop/oci > /dev/null
