name: Installers

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            distro-info \
            debhelper \
            aptitude \
            sbuild \
            schroot \
            debian-archive-keyring \
            git-buildpackage \
            rename
          sudo usermod -a -G sbuild "$(whoami)"

      - name: Build deb package
        # the user executing sbuild needs to be in the group sbuild, a relogin is not possible here
        shell: /usr/bin/sg sbuild -c "/usr/bin/bash -e {0}"
        run: |
          env | sort