name: Installers

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo rm /var/lib/man-db/auto-update
          sudo apt-get update
          sudo apt-get install -y \
            distro-info \
            debhelper \
            aptitude \
            sbuild \
            schroot \
            debian-archive-keyring \
            git-buildpackage \
            rename
          sudo usermod -p "*" sbuild
          sudo usermod -a -G sbuild "$(whoami)"
          sudo usermod -a -G sbuild "runneradmin"
          sudo cat /etc/passwd
          sudo cat /etc/shadow
          sudo cat /etc/group

      - name: Build deb package
        # the user executing sbuild needs to be in the group sbuild, a relogin is not possible here
        shell: sudo /usr/bin/sg sbuild -c "/usr/bin/bash -e {0}"
        run: |
          env | sort